//// <auto-generated />
//using System;
//using LocadoraFilmes.API.Models;
//using LocadoraFilmes.Infra.Data.Context;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace LocadoraFilmes.API.Migrations
//{
//    [DbContext(typeof(MSSQLContext))]
//    [Migration("20240511011645_updateEntities")]
//    partial class updateEntities
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("ProductVersion", "5.0.17")
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Cliente", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Cpf")
//                        .IsRequired()
//                        .HasMaxLength(14)
//                        .HasColumnType("nvarchar(14)");

//                    b.Property<string>("Nome")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Clientes");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Filme", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<bool>("Ativo")
//                        .HasColumnType("bit");

//                    b.Property<DateTime>("DataCriacao")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("GeneroId")
//                        .HasColumnType("int");

//                    b.Property<string>("Nome")
//                        .IsRequired()
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.HasKey("Id");

//                    b.HasIndex("GeneroId");

//                    b.ToTable("Filmes");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Genero", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<bool>("Ativo")
//                        .HasColumnType("bit");

//                    b.Property<DateTime>("DataCriacao")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Nome")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.HasKey("Id");

//                    b.ToTable("Generos");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Locacao", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int>("ClienteId")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("DataDevolucao")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("DataLocacao")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("Entregue")
//                        .HasColumnType("bit");

//                    b.HasKey("Id");

//                    b.HasIndex("ClienteId");

//                    b.ToTable("Locacoes");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.LocacaoFilme", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int>("FilmeId")
//                        .HasColumnType("int");

//                    b.Property<int>("LocacaoId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("FilmeId");

//                    b.HasIndex("LocacaoId");

//                    b.ToTable("LocacaoFilmes");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Filme", b =>
//                {
//                    b.HasOne("LocadoraFilmes.API.Models.Genero", "Genero")
//                        .WithMany("Filmes")
//                        .HasForeignKey("GeneroId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Genero");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Locacao", b =>
//                {
//                    b.HasOne("LocadoraFilmes.API.Models.Cliente", "Cliente")
//                        .WithMany("Locacoes")
//                        .HasForeignKey("ClienteId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Cliente");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.LocacaoFilme", b =>
//                {
//                    b.HasOne("LocadoraFilmes.API.Models.Filme", "Filme")
//                        .WithMany("LocacaoFilmes")
//                        .HasForeignKey("FilmeId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("LocadoraFilmes.API.Models.Locacao", "Locacao")
//                        .WithMany("LocacaoFilmes")
//                        .HasForeignKey("LocacaoId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Filme");

//                    b.Navigation("Locacao");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Cliente", b =>
//                {
//                    b.Navigation("Locacoes");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Filme", b =>
//                {
//                    b.Navigation("LocacaoFilmes");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Genero", b =>
//                {
//                    b.Navigation("Filmes");
//                });

//            modelBuilder.Entity("LocadoraFilmes.API.Models.Locacao", b =>
//                {
//                    b.Navigation("LocacaoFilmes");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
